<?php 


return [
    'php',
    'javascript',
    'python',
    'java',
    'c#',
    'ruby',
    'go',
    'rust',
    'kotlin',
    'swift',
    'objective-c',
    'mysql',
    'postgresql',
    'elasticsearch',
    'aws',
    'azure',
    'google cloud', // إضافة منصة سحابية أخرى
    'digitalocean', // إضافة منصة سحابية أخرى
    'docker',
    'kubernetes',
    'terraform',
    'ansible', // أداة أخرى لإدارة البنية التحتية
    'serverless',
    'microservices',
    'restful api',
    'graphql',
    'nodejs',
    'react',
    'angular',
    'vue',
    'flutter',
    'react native',
    'html',
    'css',
    'sass',
    'less',
    'bootstrap',
    'tailwind css',
    'jquery',
    'typescript',
    'mongodb',
    'redis',
    'kafka',
    'machine learning',
    'data science',
    'artificial intelligence',
    'big data',
    'cybersecurity',
    'devops',
    'agile',
    'scrum',
    'git',
    'version control'
];